# Generated by Django 2.2.4 on 2019-08-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bg', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Bulgarian)')),
                ('title_hr', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Croatian)')),
                ('title_cs', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Czech)')),
                ('title_da', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Danish)')),
                ('title_nl', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Dutch)')),
                ('title_en', models.CharField(db_tablespace='', max_length=200, verbose_name='Title (English)')),
                ('title_et', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Estonian)')),
                ('title_fi', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Finnish)')),
                ('title_fr', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (French)')),
                ('title_de', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (German)')),
                ('title_el', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Greek)')),
                ('title_hu', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Hungarian)')),
                ('title_ga', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Irish)')),
                ('title_it', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Italian)')),
                ('title_lv', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Latvian)')),
                ('title_lt', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Lithuanian)')),
                ('title_mt', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Maltese)')),
                ('title_pl', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Polish)')),
                ('title_pt', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Portuguese)')),
                ('title_ro', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Romanian)')),
                ('title_sk', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovak)')),
                ('title_sl', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovene)')),
                ('title_es', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Spanish)')),
                ('title_sv', models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Swedish)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
