# Generated by Django 2.2.4 on 2019-08-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_copy_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
    ]
