# Generated by Django 3.0 on 2019-12-14 03:00

from django.db import migrations, models
import myproject.apps.music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=250, verbose_name='Artist')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=myproject.apps.music.models.upload_to, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'unique_together': {('artist', 'title')},
            },
        ),
    ]
