# Generated by Django 3.0.1 on 2019-12-22 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViralVideo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('uuid', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('embed_code', models.TextField(blank=True, verbose_name='YouTube embed code')),
                ('anonymous_views', models.PositiveIntegerField(default=0, verbose_name='Anonymous impressions')),
                ('authenticated_views', models.PositiveIntegerField(default=0, verbose_name='Authenticated impressions')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Viral video',
                'verbose_name_plural': 'Viral videos',
            },
        ),
    ]
