# Generated by Django 3.0b1 on 2019-10-20 22:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('publishing_status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1, verbose_name='Publishing status')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
